name: SmartSeq3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - pymdown-extensions=7.1=pyh9f0ad1d_0
  - conda-forge::biopython=1.78
  - bioconda::python-sortedcontainers=2.3.0

  - bioconda::subread=2.0.1
  - bioconda::samtools=1.11
  - bioconda::star=2.7.6a
  - bioconda::umi_tools=1.1.1
  - bioconda::cutadapt=3.1
  - bioconda::seqkit=0.14.0
  - bioconda::rseqc=4.0.0
  - bioconda::deeptools=3.5.0
  - bioconda::multiqc=1.9

  - conda-forge::r-base=4.0.3
  - conda-forge::r-stringi=1.5.3
  - conda-forge::r-reshape2=1.4.4
  - bioconda::bioconductor-dropletutils=1.10.0
  - conda-forge::r-plotrix=3.8_1
  - conda-forge::r-dplyr=1.0.3
  - conda-forge::r-matrix=1.3_2
  - conda-forge::r-seurat=4.0.0
