name: SmartSeq3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.10
  - conda-forge::pymdown-extensions=8.0.1
  - bioconda::subread=1.6.2
  - bioconda::samtools=1.10
  - bioconda::star=2.7.2b
  - bioconda::umi_tools=1.1.1
  - bioconda::cutadapt=3.1
  - bioconda::biopython=1.70
  - bioconda::python-sortedcontainers=2.1.0
  - bioconda::seqkit=0.14.0
  - conda-forge::numpy=1.14.6
  # need numpy installed prior to install pyBigWig (rseqc)
  - bioconda::rseqc=3.0.1
  - bioconda::multiqc=1.8
  - bioconda::deeptools=3.5.0
  # R-packages
  - conda-forge::r-base=3.6.1
  - r::r-stringi=1.4.3
  - conda-forge::r-reshape2=1.4.4
  - bioconda::bioconductor-dropletutils=1.6.1
  - conda-forge::r-plotrix=3.7_8
  - conda-forge::r-dplyr=1.0.2
  - conda-forge::r-matrix=1.2_18
  - conda-forge::r-seurat=3.2.2
