#
# RNA-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:

    stats:
      file_format: 'csv'
      section_name: 'General Metrics'
      description: ' of sequenced data'
      plot_type: 'table'
      pconfig:
          namespace: 'stats'
          id: 'stats'
          title: 'General Statistics'
          save_file: true
          col1_header: 'Sample ID'
          headers:
              Sample_name:
                title: 'Sample Name'
                scale: false
                placement: 2000
              Number_of_reads:
                title: 'Total Reads'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 3000
              Percent_UMIs:
                title: 'UMIs reads (%)'
                min: 0
                max: 100
                scale: 'YlGnBu'
                suffix: '%'
                format: '{:,.1f}'
                placement: 4000
              Percent_Aligned:
                title: 'Aligned (%)'
                min: 0
                max: 100
                scale: 'RdYlGn'
                suffix: '%'
                format: '{:,.1f}'
                placement: 5000
              Percent_Assigned:
                title: 'Assigned (%)'
                min: 0
                max: 100
                scale: 'RdYlGn'
                suffix: '%'
                format: '{:,.1f}'
                placement: 6000
              nbUmis:
                title: '# UMIs'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 7000
              nbGenes:
                title: '# Genes'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 8000
    
    final:
      file_format: 'csv'
      section_name: 'Mapping summary'
      description: ''
      plot_type: 'bargraph'
      pconfig:
        id: 'final'
        title: 'Mapping summary'

    umiPerGene: 
      file_format: 'csv'
      section_name: 'Number of UMIs per Gene'
      description: ''
      plot_type: 'linegraph'
      pconfig:
        id: 'umiPerGene'
        title: 'Distribution of the number of UMI per gene'
    
    nbGene_perCell: 
      file_format: 'csv'
      section_name: 'Number of genes per Cell'
      description: 'Genes are those found in umi matrices.'
      plot_type: 'bargraph'
      pconfig:
        id: 'nbGene_perCell'
        title: 'Number of genes per Cell'

    nbUmi_perCell: 
      file_format: 'csv'
      section_name: 'Number of UMIs per Cell'
      description: ''
      plot_type: 'bargraph'
      pconfig:
        id: 'nbUmi_perCell'
        title: 'Number of UMIs per Cell'
        
    ratio: 
      file_format: 'csv'
      section_name: 'Ratio of the number of genes and UMIs per Cell'
      description: ''
      plot_type: 'scatter'
      pconfig:
        id: 'ratio'
        title: 'Number of genes and UMIs per Cell'
    
    mt: 
      file_format: 'csv'
      section_name: 'Percentage of mitochondrial genes per cell'
      description: 'The percentage of mitochondrial is a cell viability marker.'
      plot_type: 'scatter'
      pconfig:
        id: 'mt'
        title: 'Percentage of mitochondrial genes per cell'

sp:
  stats:
      fn: 'table_mqc.stats'
  final:
      fn: 'final_mqc.stats'
  umiPerGene:
      fn: '*_HistUMIperGene_mqc.csv'
  nbGene_perCell:
      fn: 'nbGenePerCell.csv'
  nbUmi_perCell:
      fn: 'nbUMIPerCell.csv'
  ratio:
      fn: 'RatioPerCell.csv'
  mt:
      fn: 'MtGenePerCell.csv'


###############################
## Modules 

module_order:
  - cutadapt
  - star:
      name: 'Read alignments'
      info: 'Each read is aligned on a reference genome using the STAR software.'
  - featureCounts:
      name: 'Read assignments'
      info: 'Each aligned read is assigned to a gene using the featureCounts software.'
  - deeptools
  - rseqc

#############################
## Display

report_section_order:
  # summary table
  stats:
    order: 850
  # mapping:
  final:
    order: 800
  star:
    order: 750
  featureCounts:
    order: 700
  cutadapt:
    order: 650
  deeptools:
    order: 600
  rseqc:
    order: 550
  # cell analysis
  umiPerGene:
    order: 500
  nbGene_perCell:
    order: 450
  nbUmi_perCell:
    order: 400
  ratio:
    order: 350
  mt:
    order: 300
  software_versions:
    order: -1500
  summary:
    order: -2000

plots_force_interactive: True
