#
# SmartSeq3 config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:
    stats:
      file_format: 'csv'
      section_name: 'General Metrics'
      description: 'Result summaries of each cell. The number of fragments is the number of cDNA sequenced. It is the sequencing depth. The percentage of UMIs is the proportion of fragments having tag-UMI-GGG pattern within their sequences. At least 50% are expected to have a UMI. Alignment is made on non UMI and UMI reads and should be around 70%. The assignment is made on correctly aligned reads and should be arround 60%. The number of genes is calculated from UMI reads only. A minimum of 5 000 genes and 30 000 UMIs are expected.'
      plot_type: 'table'
      pconfig:
          namespace: 'stats'
          id: 'stats'
          title: 'General Statistics'
          save_file: true
          col1_header: 'Sample ID'
      headers:
          Sample_name:
            title: 'Sample Name'
            scale: false
            placement: 2000
          Number_of_reads:
            title: 'Total Fragments'
            scale: 'YlGnBu'
            format: '{:,.0f}'
            placement: 3000
          Percent_UMIs:
            title: 'UMI reads (%)'
            min: 0
            max: 100
            scale: 'Purples'
            suffix: '%'
            format: '{:,.1f}'
            placement: 4000
          Percent_Aligned:
            title: 'Aligned (%)'
            min: 0
            max: 100
            scale: 'Greens'
            suffix: '%'
            format: '{:,.1f}'
            placement: 5000
          Percent_Assigned:
            title: 'Assigned (%)'
            min: 0
            max: 100
            scale: 'YlGn'
            suffix: '%'
            format: '{:,.1f}'
            placement: 6000
          Number_of_UMIs:
            title: 'UMIs'
            scale: 'Oranges'
            format: '{:,.0f}'
            placement: 7000
          Number_of_genes:
            title: 'Genes'
            scale: 'RdPu'
            format: '{:,.0f}'
            placement: 8000

    final:
      file_format: 'csv'
      section_name: 'Mapping summary'
      description: 'Overview of mapping steps corresponding to alignment & assignment. The alignment is done on all reads (UMI and non UMI reads). Correct reads are aligned on the genome and assigned to a gene.'
      plot_type: 'bargraph'
      pconfig:
        id: 'final'
        title: 'Mapping summary'

    umiPerGene: 
      file_format: 'csv'
      section_name: 'Expression level'
      title: 'Number of UMIs per gene'
      description: 'Distribution of the number of UMIs per gene in each sample. Genes having more than 70 UMIs (x axis) are not shown. Most genes have between one and 10 UMIs and a bend can be observed around 5.'
      plot_type: 'linegraph'
      pconfig:
        id: 'umiPerGene'
        title: ''
        xlab: 'Number of UMIs per gene'
        xmax: 70
        ylab: 'Number of genes'
        #xLog: True
        #logswitch: True
        #logswitch_active: True
        #logswitch_label: 'Log10'
        #reversedStacks: True

    nbGene_perCell: 
      file_format: 'csv'
      section_name: 'Library complexity'
      title: 'Number of genes per cell'
      description: 'Genes are those found in the UMI matrices (non UMI reads are not take into account). In SmartSeq3, cells should have more than 5000 genes.'
      plot_type: 'bargraph'
      pconfig:
        id: 'nbGene_perCell'
        title: 'Number of genes per cell'

    nbUmi_perCell: 
      file_format: 'csv'
      section_name: 'Number of UMIs per cell'
      description: 'At least 30 000 UMIs are expected.'
      plot_type: 'bargraph'
      pconfig:
        id: 'nbUmi_perCell'
        title: 'Number of UMIs per cell'
        
    ratio: 
      file_format: 'csv'
      section_name: 'Library complexity'
      section_name: 'Number of genes & UMIs per cell'
      description: 'A scatter plot of the ratio of the number of genes and UMIs per cell allow an easy representation of a cell composition.'
      plot_type: 'scatter'
      pconfig:
        id: 'ratio'
        title: 'Number of genes and UMIs per cell'
        xlab: 'Number of UMIs'
        ylab: 'Number of genes'

    mt: 
      file_format: 'csv'
      section_name: 'Cell viability'
      title: '% Mitochondrial RNAs per cell'
      description: 'Percentage of mitochondrial RNAs is a cell viability marker. It varies according your cell type (e.g cell line, primary cells, etc.). Here, only UMI reads are take into account.'
      plot_type: 'scatter'
      pconfig:
        id: 'mt'
        title: 'Percentage of mitochondrial RNAs per cell'
        xlab: 'Number of genes'
        ylab: '% mitochondrial RNAs'

    gene_saturation:
       file_format: 'tsv'
       section_name: 'Gene-based saturation'
       description: 'plot showing the number of detected genes for a given set of subsampling values.'
       plot_type: 'linegraph'
       pconfig:
            namespace: 'gene saturation'
            id: 'genesaturation'
            title: 'Gene-based Saturation'
            ylab: 'Number of detected genes'
            xlab: 'Number of UMIs (normalized per thousand)'


sp:
  stats:
      fn: 'table_mqc.stats'
  final:
      fn: 'final_mqc.stats'
  umiPerGene:
      fn: '*_HistUMIperGene_mqc.csv'
  nbGene_perCell:
      fn: 'nbGenePerCell.csv'
  nbUmi_perCell:
      fn: 'nbUMIPerCell.csv'
  ratio:
      fn: 'RatioPerCell.csv'
  mt:
      fn: 'MtGenePerCell.csv'
  gene_saturation:
      fn: '*gcurve.txt'



###############################
## Modules 

module_order:
  - cutadapt
  - star
  - featurecounts
  - preseq:
     name: 'Sequencing Complexity'
     info: 'estimates the complexity of a library, showing how many additional unique reads are sequenced for increasing total read count. A shallow curve indicates complexity saturation. The dashed line shows a perfectly complex library where total reads = unique reads. The presented graph shows extrapolated curves up to 200M sequencing reads.'
  - deeptools
  - rseqc

#############################
## Display

report_section_order:
  # summary table
  stats:
    order: 850
  # mapping:
  final:
    order: 800
  star:
    order: 750
  featurecounts:
    order: 700
  cutadapt:
    order: 650
  rseqc:
    order: 550
  # cell analysis
  umiPerGene:
    order: 500
  nbGene_perCell:
    order: 450
  nbUmi_perCell:
    order: 400
  ratio:
    order: 350
  mt:
    order: 300
  software_versions:
    order: -1500
  summary:
    order: -2000

plots_force_interactive: True
