#
# RNA-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:

    stats:
      file_format: 'csv'
      section_name: 'General Metrics'
      description: ' of sequenced data'
      plot_type: 'table'
      pconfig:
          namespace: 'stats'
          id: 'stats'
          title: 'General Statistics'
          save_file: true
          col1_header: 'Sample ID'
          headers:
              Sample_name:
                title: 'Sample Name'
                scale: false
                placement: 2000
              Number_of_reads:
                title: 'Total Reads'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 3000
              Percent_UMIs:
                title: 'UMIs (%)'
                min: 0
                max: 100
                scale: 'RdYlGn'
                suffix: '%'
                format: '{:,.1f}'
                placement: 4000
              Percent_Aligned:
                title: 'Aligned (%)'
                min: 0
                max: 100
                scale: 'RdYlGn'
                suffix: '%'
                format: '{:,.1f}'
                placement: 5000
              Percent_Assigned:
                title: 'Assigned (%)'
                min: 0
                max: 100
                scale: 'RdYlGn'
                suffix: '%'
                format: '{:,.1f}'
                placement: 6000
              Cell_tot:
                title: 'Cells tot.'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 7000

sp:
   stats:
      fn: 'table_mqc.stats'


###############################
## Modules 

module_order:
  - fastqc
  - bowtie1:
      name: 'rRNA Mapping'
      info: 'This section reports the fraction of reads aligned on ribosomal RNAs.'
      target: ''
      path_filters:
        - '*.log'
  - star
  - hisat2
  - tophat
  - rseqc
  - featureCounts
  - HTSeq
  - preseq:
     name: 'Sequencing Complexity'
     info: 'estimates the complexity of a library, showing how many additional unique reads are sequenced for increasing total read count. A shallow curve indicates complexity saturation. The dashed line shows a perfectly complex library where total reads = unique reads. The presented graph shows extrapolated curves up to 200M sequencing reads.'


custom_plot_config:
   bowtie1_alignment:
     reads_aligned:
       color: '#e41a1c'
     multimapped:
       color: '#ffffb3'
     not_aligned:
       color: '#1f78b4'

   rseqc_read_distribution_plot:
     cds_exons_tag_count:
        color: '#8dd3c7'
     5_utr_exons_tag_count:
        color: '#ffffb3'
     3_utr_exons_tag_count:
        color: '#bebada'
     introns_tag_count:
        color: '#fb8072'
     tss_up_1kb_tag_count:
        color: '#80b1d3'
     tss_up_5kb_tag_count:
        color: '#fdb462'
     tss_up_10kb_tag_count:
        color: '#b3dde69'
     tes_down_1kb_tag_count:
        color: '#fccde5'
     tes_down_5kb_tag_count:
        color: '#d9d9d9'
     tes_down_10kb_tag_count:
        color: '#bc80bd'
     other_intergenic_tag_count:
        color: '#ccebc5'


#############################
## Display

report_section_order:
  stats:
    order: 1
  gene_saturation:
    order: -400
  gene_type:
    order: -500
  DupRadar:
    order: -600 
  sample-pca:
    order: -800
  sample-correlation:
    order: -900
  software_versions:
    order: -1000
  summary:
    order: -1100

table_columns_visible:
    FastQC:
        percent_duplicates: False

preseq:
   notrim: true

plots_force_interactive: True
