#
# RNA-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:

    stats:
      file_format: 'csv'
      section_name: 'General Metrics'
      description: ' of sequenced data'
      plot_type: 'table'
      pconfig:
          namespace: 'stats'
          id: 'stats'
          title: 'General Statistics'
          save_file: true
          col1_header: 'Sample ID'
          headers:
              Sample_name:
                title: 'Sample Name'
                scale: false
                placement: 2000
              Number_of_reads:
                title: 'Total Reads'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 3000
              Percent_UMIs:
                title: 'UMIs reads (%)'
                min: 0
                max: 100
                scale: 'YlGnBu'
                suffix: '%'
                format: '{:,.1f}'
                placement: 4000
              Percent_Aligned:
                title: 'Aligned (%)'
                min: 0
                max: 100
                scale: 'RdYlGn'
                suffix: '%'
                format: '{:,.1f}'
                placement: 5000
              Percent_Assigned:
                title: 'Assigned (%)'
                min: 0
                max: 100
                scale: 'RdYlGn'
                suffix: '%'
                format: '{:,.1f}'
                placement: 6000
              nbUmis:
                title: '# UMIs'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 7000
              nbGenes:
                title: '# Genes'
                scale: 'YlGnBu'
                format: '{:,.0f}'
                placement: 8000
    
    final:
      file_format: 'csv'
      section_name: 'Mapping summary'
      description: ''
      plot_type: 'bargraph'
      pconfig:
        id: 'final'
        title: 'Mapping summary'

sp:
  stats:
      fn: 'table_mqc.stats'
  final:
      fn: 'final_mqc.stats'


###############################
## Modules 

module_order:
  - cutadapt
  - star:
      name: 'Read alignments'
      info: 'Each read is aligned on a reference genome using the STAR software.'
  - featureCounts:
      name: 'Read assignments'
      info: 'Each aligned read is assigned to a gene using the featureCounts software.'
  - deeptools
  - rseqc

custom_plot_config:
   rseqc_read_distribution_plot:
     cds_exons_tag_count:
        color: '#8dd3c7'
     5_utr_exons_tag_count:
        color: '#ffffb3'
     3_utr_exons_tag_count:
        color: '#bebada'
     introns_tag_count:
        color: '#fb8072'
     tss_up_1kb_tag_count:
        color: '#80b1d3'
     tss_up_5kb_tag_count:
        color: '#fdb462'
     tss_up_10kb_tag_count:
        color: '#b3dde69'
     tes_down_1kb_tag_count:
        color: '#fccde5'
     tes_down_5kb_tag_count:
        color: '#d9d9d9'
     tes_down_10kb_tag_count:
        color: '#bc80bd'
     other_intergenic_tag_count:
        color: '#ccebc5'


#############################
## Display

report_section_order:
  stats:
    order: 100
  software_versions:
    order: -1000
  summary:
    order: -1100

plots_force_interactive: True
